### PR TITLE
custom-ipxe: add packet-cli example

### PR DESCRIPTION
**Pull request by dustinmiller1337**

### CODE REVIEW

**Comment by displague** [comment]
This is helpful. I had to lookup `custom_ipxe` myself to confirm https://github.com/packethost/packet-cli/pull/88

Would this be better homed in the packet-cli README.md or here? If the answer is here, we should consider moving more examples and documentation from that README.md and referring to these docs.

**Comment by dustinmiller1337** [comment]
Why both both? 🤷 😀  but also I believe this example belongs here as part of the image guide 🙂

**Review by DailyAlice — APPROVED** [review]
haven't tested, but I think it looks good to go here.

**Comment by displague** [comment]
Thanks, @dustinmiller1337!

**Pull request merged**
